package gregicality.multiblocks.api.fluids;

import java.util.Collection;

import net.minecraft.client.renderer.texture.TextureMap;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.fluids.Fluid;

import org.jetbrains.annotations.NotNull;

import gregtech.api.GregTechAPI;
import gregtech.api.fluids.MetaFluids;
import gregtech.api.unification.material.Material;
import gregtech.api.unification.material.properties.BlastProperty;
import gregtech.api.unification.material.properties.PropertyKey;
import gregtech.api.unification.ore.OrePrefix;

import gregicality.multiblocks.GregicalityMultiblocks;
import gregicality.multiblocks.api.fluids.fluidType.GCYMFluidTypes;
import gregicality.multiblocks.api.unification.GCYMMaterialFlags;
import gregicality.multiblocks.api.unification.properties.AlloyBlastProperty;
import gregicality.multiblocks.api.unification.properties.GCYMPropertyKey;

import it.unimi.dsi.fastutil.objects.ObjectOpenHashSet;

public final class GCYMMetaFluids {

    private static final Collection<ResourceLocation> fluidSprites = new ObjectOpenHashSet<>();

    public static final ResourceLocation AUTO_GENERATED_MOLTEN_TEXTURE = new ResourceLocation(
            GregicalityMultiblocks.MODID, "blocks/fluids/fluid.molten.autogenerated");

    private GCYMMetaFluids() {}

    public static void init() {
        fluidSprites.add(AUTO_GENERATED_MOLTEN_TEXTURE);

        for (Material material : GregTechAPI.materialManager.getRegisteredMaterials()) {
            createMoltenFluid(material);
        }
    }

    public static void createMoltenFluid(@NotNull Material material) {
        // ignore materials set not to be alloy blast handled
        if (material.hasFlag(GCYMMaterialFlags.DISABLE_ALLOY_PROPERTY)) return;

        // ignore materials which are not alloys
        if (material.getMaterialComponents().size() <= 1) return;

        final BlastProperty blastProperty = material.getProperty(PropertyKey.BLAST);
        if (blastProperty == null) return;

        final AlloyBlastProperty alloyBlastProperty = material.getProperty(GCYMPropertyKey.ALLOY_BLAST);
        if (alloyBlastProperty == null) return;

        if (OrePrefix.ingotHot.doGenerateItem(material)) {
            // use molten texture instead of iconset textures
            MetaFluids.setMaterialFluidTexture(material, GCYMFluidTypes.MOLTEN, AUTO_GENERATED_MOLTEN_TEXTURE);

            int temperature = blastProperty.getBlastTemperature();
            Fluid fluid = MetaFluids.registerFluid(material, GCYMFluidTypes.MOLTEN, temperature, false);

            alloyBlastProperty.setFluid(fluid);
        } else if (material.hasProperty(PropertyKey.FLUID)) {
            // not hot enough to produce molten fluid, so produce regular fluid
            alloyBlastProperty.setFluid(material.getFluid());
        } else return;

        alloyBlastProperty.setTemperature(blastProperty.getBlastTemperature());
    }

    public static void registerSprites(@NotNull TextureMap textureMap) {
        fluidSprites.forEach(textureMap::registerSprite);
    }
}
