package gregicality.multiblocks.loaders.recipe;

import static gregtech.api.unification.material.Materials.Graphene;
import static gregtech.api.unification.ore.OrePrefix.dust;
import static gregtech.api.unification.ore.OrePrefix.foil;

import gregtech.api.recipes.RecipeMaps;
import gregtech.common.items.MetaItems;

public final class GCYMMiscRecipes {

    private GCYMMiscRecipes() {}

    public static void init() {
        grapheneRecipes();
    }

    /**
     * Recipes for graphene that don't get autogenerated
     */
    private static void grapheneRecipes() {
        // Foil Extruding
        RecipeMaps.EXTRUDER_RECIPES.recipeBuilder()
                .input(dust, Graphene)
                .notConsumable(MetaItems.SHAPE_EXTRUDER_FOIL)
                .output(foil, Graphene, 4)
                .duration((int) Graphene.getMass())
                .EUt(24)
                .buildAndRegister();
    }
}
